### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by lionelfleury** [bazeltools/bazel-deps#334]
- Readme still uses `--sha-file` in usage.
- `update_dependencies.sh` script as well

Maybe update the documentation on how to use the tool with no sha file...

**Comment by johnynek** [comment]
can you try to take a look at this portion of the README:

https://github.com/bazeltools/bazel-deps#alternate-outputs-external-repo

it describes how to use `-disable-3rdparty-in-repo`

that said it still uses the `-s` or `--sha-file` option.

Reviewing now, it seems you would only not use the `--sha-file` option for truly custom setups where instead you get a json file with the full resolution and then you write custom code in your repo. That is actually what we are doing at my work now because what often happens with a monorepo is that you have to solve some special snowflake problems that others don't have. By just consuming the json lock file you can do that yourself.

**Comment by johnynek** [comment]
I added this note in the readme explaining something about `--resolved-output`.

https://github.com/bazeltools/bazel-deps#customized-integration

**Comment by lionelfleury** [comment]
Thanks for the explanation. 👍 
Appreciate.
